# permissions for end users to edit maintenancemodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maintenancemode-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maintenance-controller
    app.kubernetes.io/part-of: maintenance-controller
    app.kubernetes.io/managed-by: kustomize
  name: maintenancemode-editor-role
rules:
- apiGroups:
  - cluster.rcluff.com
  resources:
  - maintenancemodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rcluff.com
  resources:
  - maintenancemodes/status
  verbs:
  - get
