---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cluster.rcluff.com
  resources:
  - maintenancemodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.rcluff.com
  resources:
  - maintenancemodes/finalizers
  verbs:
  - update
- apiGroups:
  - cluster.rcluff.com
  resources:
  - maintenancemodes/status
  verbs:
  - get
  - patch
  - update
